image:
  file: .gitpod.Dockerfile

tasks:
  - name: dev
    init: |
      pnpm install
      echo "NEXTAUTH_URL=$(gp url 3000)" > .env.local
      echo "NEXTAUTH_URL_INTERNAL=http://localhost:3000" >> .env.local
      pnpm run db:migrate
      pnpm run db:seed
    command: |
      pnpm exec playwright install
      pnpm run dev

vscode:
  extensions:
    - anwar.papyrus-pdf
    - csstools.postcss
    - davidanson.vscode-markdownlint
    - dbaeumer.vscode-eslint
    - dsznajder.es7-react-js-snippets
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - formulahendry.auto-rename-tag
    - jock.svg
    - lokalise.i18n-ally
    - meganrogge.template-string-converter
    - mgmcdermott.vscode-language-babel
    - mhutchie.git-graph
    - mikestead.dotenv
    - ms-playwright.playwright
    - prisma.prisma
    - streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker-german
    - streetsidesoftware.code-spell-checker-medical-terms
    - stylelint.vscode-stylelint
    - vunguyentuan.vscode-postcss
    - wayou.vscode-todo-highlight
