image:
  file: .gitpod.Dockerfile

additionalRepositories:
  - url: https://github.com/medreporter/medtl

tasks:
  - name: Dev
    init: |
      pnpm install
      echo "NEXTAUTH_URL=$(gp url 3000)" > .env.local
      echo "NEXTAUTH_URL_INTERNAL=http://localhost:3000" >> .env.local
      pnpm db:migrate
      pnpm db:seed
      gp sync-done install
    command: pnpm run dev
  - name: MedTL
    before: cd ../medtl
    init: |
      pnpm install
      pnpm build

vscode:
  extensions:
    - anwar.papyrus-pdf
    - davidanson.vscode-markdownlint
    - dbaeumer.vscode-eslint
    - dsznajder.es7-react-js-snippets
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - formulahendry.auto-rename-tag
    - jock.svg
    - lokalise.i18n-ally
    - meganrogge.template-string-converter
    - mgmcdermott.vscode-language-babel
    - mhutchie.git-graph
    - mikestead.dotenv
    - ms-playwright.playwright
    - prisma.prisma
    - streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker-german
    - streetsidesoftware.code-spell-checker-medical-terms
    - wayou.vscode-todo-highlight
