# Use custom Dockerfile
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Dev
    before: |
      echo "@medreporter:registry=https://$NPM_REGISTRY_HOST/" > ~/.npmrc
      echo "//$NPM_REGISTRY_HOST/:_authToken=\"$NPM_REGISTRY_TOKEN\"" >> ~/.npmrc
    init: |
      yarn install
      blitz prisma migrate dev
      blitz db seed
      gp sync-done install
    command: yarn dev
  - name: Test
    init: gp sync-await install
    command: yarn test:watch

vscode:
  extensions:
    - davidanson.vscode-markdownlint
    - dbaeumer.vscode-eslint
    - dsznajder.es7-react-js-snippets
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - formulahendry.auto-rename-tag
    - jock.svg
    - lokalise.i18n-ally
    - meganrogge.template-string-converter
    - mgmcdermott.vscode-language-babel
    - mhutchie.git-graph
    - mikestead.dotenv
    - orta.vscode-jest
    - prisma.prisma
    - streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker-german
    - tomoki1207.pdf
    - wayou.vscode-todo-highlight
